"""
fraud_model.py

Fraud Risk Score layer. Reads ONLY from the canonical dict (never raw vendor
payloads), matching the same contract the rules engine uses. Two modes:

  - trained: loads a pickled/MLflow-tracked model (train it on the 100K master
    dataset -- see data/master_dataset_adapter.py and the build guide's
    Section 8 for the training script).
  - heuristic: a transparent, hand-weighted fallback used until a trained
    model is available, so the pipeline is runnable end-to-end from day one.
"""

from __future__ import annotations
import os
from typing import Any

MODEL_PATH = os.environ.get("FRAUD_MODEL_PATH")  # set once a trained model exists
_model = None


def _load_trained_model():
    global _model
    if _model is None and MODEL_PATH and os.path.exists(MODEL_PATH):
        import joblib
        _model = joblib.load(MODEL_PATH)
    return _model


def _features_from_canonical(canonical: dict) -> dict[str, Any]:
    """Same feature set a trained model would consume -- keep this function as
    the single source of truth for both training (data/build_training_set.py)
    and inference, so features never drift between the two."""
    identity = canonical["identity"]
    owner = canonical["owner"]
    account = canonical["account"]
    supp = canonical["supplementary"]
    return {
        "record_found": int(identity["record_found"]),
        "name_match_any": int(identity["name_match_any"]),
        "ofac_hit": int(identity["ofac_hit"]),
        "identity_check_score": identity["identity_check_score"] or 0,
        "identity_network_score": identity["identity_network_score"] or 0,
        "low_identity_score": int(identity["low_identity_score"]),
        "alerts_count": identity["alerts_count"],
        "address_match": int(owner["address_match"]),
        "is_commercial_address": int(owner["is_commercial_address"]),
        "is_forwarder_address": int(owner["is_forwarder_address"]),
        "recent_previous_address_count_90d": owner["recent_previous_address_count_90d"],
        "account_verified": int(account["account_verified"]),
        "ews_fraud_history": int(account.get("ews_fraud_history") or False),
        "email_is_disposable": int(supp["email_is_disposable"]),
        "email_is_autogenerated": int(supp["email_is_autogenerated"]),
        "mailbox_velocity": supp["mailbox_velocity"] or 0,
        "ip_proxy_risk": int(supp["ip_proxy_risk"]),
        "ofac_potential_matches_count": supp["ofac_potential_matches_count"],
    }


def _heuristic_score(features: dict) -> float:
    """Transparent placeholder -- replace by pointing FRAUD_MODEL_PATH at a
    trained model. Weights here are illustrative only (see build guide 8.2-8.3
    for how to train and calibrate the real model on the 100K dataset)."""
    risk = (
        0.35 * features["ofac_hit"]
        + 0.15 * features["is_forwarder_address"]
        + 0.12 * features["ews_fraud_history"]
        + 0.10 * features["ip_proxy_risk"]
        + 0.10 * features["email_is_disposable"]
        + 0.08 * features["low_identity_score"]
        + 0.05 * min(features["mailbox_velocity"] / 10, 1.0)
        + 0.05 * min(features["ofac_potential_matches_count"] / 3, 1.0)
    )
    return round(min(risk, 0.99), 4)


def fraud_probability(canonical: dict) -> dict[str, Any]:
    features = _features_from_canonical(canonical)
    model = _load_trained_model()
    if model is not None:
        try:
            import pandas as pd
            # Named-column DataFrame, not a positional list -- avoids a
            # silent bug if this dict's key order ever drifts from the
            # order the model was trained on (train_fraud_model.py builds
            # its feature columns from this exact same function).
            X = pd.DataFrame([features])
            probability = float(model.predict_proba(X)[0][1])
            source = "trained_model"
        except Exception:
            probability = _heuristic_score(features)
            source = "heuristic_fallback_model_error"
    else:
        probability = _heuristic_score(features)
        source = "heuristic_fallback"
    return {"fraud_probability": probability, "source": source, "features": features}
